name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Coding 制品库
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.CODING_USER }}
          password: ${{ secrets.CODING_TOKEN }}

      - name: Run docker compose and Push Docker image
        uses: shining-so/compose-action@v2.2.2
        with:
          compose-file: "./docker-compose.yaml"
        env:
          DOCKER_REGISTRY: "ccr.ccs.tencentyun.com"
          IMAGE_TAG: "latest"
          NUM_WORKERS_PER_QUEUE: "8"
          PORT: "3002"
          HOST: "0.0.0.0"
          REDIS_URL: "redis://redis:6379"
          REDIS_RATE_LIMIT_URL: "redis://redis:6379"
          PLAYWRIGHT_MICROSERVICE_URL: "http://playwright-service:3000/html"
          USE_DB_AUTHENTICATION: "false"
